package eu.mshade.enderman.wrapper

import eu.mshade.enderframe.item.Material
import eu.mshade.enderframe.item.MaterialKey
import eu.mshade.enderframe.wrapper.MaterialKeyWrapper
import eu.mshade.enderframe.wrapper.MaterialWrapperContext

class EndermanMaterialKeyWrapper : MaterialKeyWrapper() {
    /**
     * Class for wrapping a MaterialKey for protocol 1.8.9
     */
    init {
        registerReverseMapping(MaterialWrapperContext.BLOCK, Material.DEAD_BUSH, MaterialKey.from(32, 0))
        registerReverseMapping(MaterialWrapperContext.BLOCK, Material.REDSTONE_LAMP, MaterialKey.from(124, 0))

        //list minecraft materials id
        register(Material.STONE, MaterialKey.from(1, 0))
        register(Material.GRANITE, MaterialKey.from(1, 1))
        register(Material.POLISHED_GRANITE, MaterialKey.from(1, 2))
        register(Material.DIORITE, MaterialKey.from(1, 3))
        register(Material.POLISHED_DIORITE, MaterialKey.from(1, 4))
        register(Material.ANDESITE, MaterialKey.from(1, 5))
        register(Material.POLISHED_ANDESITE, MaterialKey.from(1, 6))
        register(Material.GRASS_BLOCK, MaterialKey.from(2, 0))
        register(Material.DIRT, MaterialKey.from(3, 0))
        register(Material.COARSE_DIRT, MaterialKey.from(3, 1))
        register(Material.PODZOL, MaterialKey.from(3, 2))
        register(Material.COBBLESTONE, MaterialKey.from(4, 0))
        register(Material.OAK_PLANKS, MaterialKey.from(5, 0))
        register(Material.SPRUCE_PLANKS, MaterialKey.from(5, 1))
        register(Material.BIRCH_PLANKS, MaterialKey.from(5, 2))
        register(Material.JUNGLE_PLANKS, MaterialKey.from(5, 3))
        register(Material.ACACIA_PLANKS, MaterialKey.from(5, 4))
        register(Material.DARK_OAK_PLANKS, MaterialKey.from(5, 5))
        register(Material.OAK_SAPLING, MaterialKey.from(6, 0))
        register(Material.SPRUCE_SAPLING, MaterialKey.from(6, 1))
        register(Material.BIRCH_SAPLING, MaterialKey.from(6, 2))
        register(Material.JUNGLE_SAPLING, MaterialKey.from(6, 3))
        register(Material.ACACIA_SAPLING, MaterialKey.from(6, 4))
        register(Material.DARK_OAK_SAPLING, MaterialKey.from(6, 5))
        register(Material.BEDROCK, MaterialKey.from(7, 0))
        register(Material.SAND, MaterialKey.from(12, 0))
        register(Material.RED_SAND, MaterialKey.from(12, 1))
        register(Material.GRAVEL, MaterialKey.from(13, 0))
        register(Material.GOLD_ORE, MaterialKey.from(14, 0))
        register(Material.IRON_ORE, MaterialKey.from(15, 0))
        register(Material.COAL_ORE, MaterialKey.from(16, 0))
        register(Material.OAK_WOOD, MaterialKey.from(17, 0))
        register(Material.SPRUCE_WOOD, MaterialKey.from(17, 1))
        register(Material.BIRCH_WOOD, MaterialKey.from(17, 2))
        register(Material.JUNGLE_WOOD, MaterialKey.from(17, 3))
        register(Material.OAK_LEAVES, MaterialKey.from(18, 0))
        register(Material.SPRUCE_LEAVES, MaterialKey.from(18, 1))
        register(Material.BIRCH_LEAVES, MaterialKey.from(18, 2))
        register(Material.JUNGLE_LEAVES, MaterialKey.from(18, 3))
        register(Material.SPONGE, MaterialKey.from(19, 0))
        register(Material.WET_SPONGE, MaterialKey.from(19, 1))
        register(Material.GLASS, MaterialKey.from(20, 0))
        register(Material.LAPIS_ORE, MaterialKey.from(21, 0))
        register(Material.LAPIS_BLOCK, MaterialKey.from(22, 0))
        register(Material.DISPENSER, MaterialKey.from(23, 0))
        register(Material.SANDSTONE, MaterialKey.from(24, 0))
        register(Material.CHISELED_SANDSTONE, MaterialKey.from(24, 1))
        register(Material.SMOOTH_SANDSTONE, MaterialKey.from(24, 2))
        register(Material.NOTE_BLOCK, MaterialKey.from(25, 0))
        register(Material.POWERED_RAIL, MaterialKey.from(27, 0))
        register(Material.DETECTOR_RAIL, MaterialKey.from(28, 0))
        register(Material.STICKY_PISTON, MaterialKey.from(29, 0))
        register(Material.COBWEB, MaterialKey.from(30, 0))
        register(Material.DEAD_BUSH, MaterialKey.from(31, 0))
        register(Material.TALL_GRASS, MaterialKey.from(31, 1))
        register(Material.FERN, MaterialKey.from(31, 2))
        register(Material.PISTON, MaterialKey.from(33, 0))
        register(Material.WHITE_WOOL, MaterialKey.from(35, 0))
        register(Material.ORANGE_WOOL, MaterialKey.from(35, 1))
        register(Material.MAGENTA_WOOL, MaterialKey.from(35, 2))
        register(Material.LIGHT_BLUE_WOOL, MaterialKey.from(35, 3))
        register(Material.YELLOW_WOOL, MaterialKey.from(35, 4))
        register(Material.LIME_WOOL, MaterialKey.from(35, 5))
        register(Material.PINK_WOOL, MaterialKey.from(35, 6))
        register(Material.GRAY_WOOL, MaterialKey.from(35, 7))
        register(Material.LIGHT_GRAY_WOOL, MaterialKey.from(35, 8))
        register(Material.CYAN_WOOL, MaterialKey.from(35, 9))
        register(Material.PURPLE_WOOL, MaterialKey.from(35, 10))
        register(Material.BLUE_WOOL, MaterialKey.from(35, 11))
        register(Material.BROWN_WOOL, MaterialKey.from(35, 12))
        register(Material.GREEN_WOOL, MaterialKey.from(35, 13))
        register(Material.RED_WOOL, MaterialKey.from(35, 14))
        register(Material.BLACK_WOOL, MaterialKey.from(35, 15))
        register(Material.DANDELION, MaterialKey.from(37, 0))
        register(Material.POPPY, MaterialKey.from(38, 0))
        register(Material.BLUE_ORCHID, MaterialKey.from(38, 1))
        register(Material.ALLIUM, MaterialKey.from(38, 2))
        register(Material.AZURE_BLUET, MaterialKey.from(38, 3))
        register(Material.RED_TULIP, MaterialKey.from(38, 4))
        register(Material.ORANGE_TULIP, MaterialKey.from(38, 5))
        register(Material.WHITE_TULIP, MaterialKey.from(38, 6))
        register(Material.PINK_TULIP, MaterialKey.from(38, 7))
        register(Material.OXEYE_DAISY, MaterialKey.from(38, 8))
        register(Material.BROWN_MUSHROOM, MaterialKey.from(39, 0))
        register(Material.RED_MUSHROOM, MaterialKey.from(40, 0))
        register(Material.GOLD_BLOCK, MaterialKey.from(41, 0))
        register(Material.IRON_BLOCK, MaterialKey.from(42, 0))
        register(Material.STONE_SLAB, MaterialKey.from(44, 0))
        register(Material.SANDSTONE_SLAB, MaterialKey.from(44, 1))
        register(Material.OAK_SLAB, MaterialKey.from(44, 2))
        register(Material.COBBLESTONE_SLAB, MaterialKey.from(44, 3))
        register(Material.BRICK_SLAB, MaterialKey.from(44, 4))
        register(Material.STONE_BRICK_SLAB, MaterialKey.from(44, 5))
        register(Material.NETHER_BRICK_SLAB, MaterialKey.from(44, 6))
        register(Material.QUARTZ_SLAB, MaterialKey.from(44, 7))
        register(Material.BRICKS, MaterialKey.from(45, 0))
        register(Material.TNT, MaterialKey.from(46, 0))
        register(Material.BOOKSHELF, MaterialKey.from(47, 0))
        register(Material.MOSSY_COBBLESTONE, MaterialKey.from(48, 0))
        register(Material.OBSIDIAN, MaterialKey.from(49, 0))
        register(Material.TORCH, MaterialKey.from(50, 0))
        register(Material.SPAWNER, MaterialKey.from(52, 0))
        register(Material.OAK_STAIRS, MaterialKey.from(53, 0))
        register(Material.CHEST, MaterialKey.from(54, 0))
        register(Material.DIAMOND_ORE, MaterialKey.from(56, 0))
        register(Material.DIAMOND_BLOCK, MaterialKey.from(57, 0))
        register(Material.CRAFTING_TABLE, MaterialKey.from(58, 0))
        register(Material.FARMLAND, MaterialKey.from(60, 0))
        register(Material.FURNACE, MaterialKey.from(61, 0))
        register(Material.LADDER, MaterialKey.from(65, 0))
        register(Material.RAIL, MaterialKey.from(66, 0))
        register(Material.STONE_STAIRS, MaterialKey.from(67, 0))
        register(Material.LEVER, MaterialKey.from(69, 0))
        register(Material.STONE_PRESSURE_PLATE, MaterialKey.from(70, 0))
        register(Material.OAK_PRESSURE_PLATE, MaterialKey.from(72, 0))
        register(Material.REDSTONE_ORE, MaterialKey.from(73, 0))
        register(Material.REDSTONE_TORCH, MaterialKey.from(76, 0))
        register(Material.STONE_BUTTON, MaterialKey.from(77, 0))
        register(Material.SNOW, MaterialKey.from(78, 0))
        register(Material.ICE, MaterialKey.from(79, 0))
        register(Material.SNOW_BLOCK, MaterialKey.from(80, 0))
        register(Material.CACTUS, MaterialKey.from(81, 0))
        register(Material.CLAY, MaterialKey.from(82, 0))
        register(Material.JUKEBOX, MaterialKey.from(84, 0))
        register(Material.OAK_FENCE, MaterialKey.from(85, 0))
        register(Material.PUMPKIN, MaterialKey.from(86, 0))
        register(Material.NETHERRACK, MaterialKey.from(87, 0))
        register(Material.SOUL_SAND, MaterialKey.from(88, 0))
        register(Material.GLOWSTONE, MaterialKey.from(89, 0))
        register(Material.JACK_O_LANTERN, MaterialKey.from(91, 0))
        register(Material.WHITE_STAINED_GLASS, MaterialKey.from(95, 0))
        register(Material.ORANGE_STAINED_GLASS, MaterialKey.from(95, 1))
        register(Material.MAGENTA_STAINED_GLASS, MaterialKey.from(95, 2))
        register(Material.LIGHT_BLUE_STAINED_GLASS, MaterialKey.from(95, 3))
        register(Material.YELLOW_STAINED_GLASS, MaterialKey.from(95, 4))
        register(Material.LIME_STAINED_GLASS, MaterialKey.from(95, 5))
        register(Material.PINK_STAINED_GLASS, MaterialKey.from(95, 6))
        register(Material.GRAY_STAINED_GLASS, MaterialKey.from(95, 7))
        register(Material.LIGHT_GRAY_STAINED_GLASS, MaterialKey.from(95, 8))
        register(Material.CYAN_STAINED_GLASS, MaterialKey.from(95, 9))
        register(Material.PURPLE_STAINED_GLASS, MaterialKey.from(95, 10))
        register(Material.BLUE_STAINED_GLASS, MaterialKey.from(95, 11))
        register(Material.BROWN_STAINED_GLASS, MaterialKey.from(95, 12))
        register(Material.GREEN_STAINED_GLASS, MaterialKey.from(95, 13))
        register(Material.RED_STAINED_GLASS, MaterialKey.from(95, 14))
        register(Material.BLACK_STAINED_GLASS, MaterialKey.from(95, 15))
        register(Material.OAK_TRAPDOOR, MaterialKey.from(96, 0))
        register(Material.INFESTED_STONE, MaterialKey.from(97, 0))
        register(Material.INFESTED_COBBLESTONE, MaterialKey.from(97, 1))
        register(Material.INFESTED_STONE_BRICKS, MaterialKey.from(97, 2))
        register(Material.INFESTED_MOSSY_STONE_BRICKS, MaterialKey.from(97, 3))
        register(Material.INFESTED_CRACKED_STONE_BRICKS, MaterialKey.from(97, 4))
        register(Material.INFESTED_CHISELED_STONE_BRICKS, MaterialKey.from(97, 5))
        register(Material.STONE_BRICKS, MaterialKey.from(98, 0))
        register(Material.MOSSY_STONE_BRICKS, MaterialKey.from(98, 1))
        register(Material.CRACKED_STONE_BRICKS, MaterialKey.from(98, 2))
        register(Material.CHISELED_STONE_BRICKS, MaterialKey.from(98, 3))
        register(Material.BROWN_MUSHROOM_BLOCK, MaterialKey.from(99, 0))
        register(Material.RED_MUSHROOM_BLOCK, MaterialKey.from(100, 0))
        register(Material.IRON_BARS, MaterialKey.from(101, 0))
        register(Material.GLASS_PANE, MaterialKey.from(102, 0))
        register(Material.MELON, MaterialKey.from(103, 0))
        register(Material.VINE, MaterialKey.from(106, 0))
        register(Material.OAK_FENCE_GATE, MaterialKey.from(107, 0))
        register(Material.BRICK_STAIRS, MaterialKey.from(108, 0))
        register(Material.STONE_BRICK_STAIRS, MaterialKey.from(109, 0))
        register(Material.MYCELIUM, MaterialKey.from(110, 0))
        register(Material.LILY_PAD, MaterialKey.from(111, 0))
        register(Material.NETHER_BRICK, MaterialKey.from(112, 0))
        register(Material.NETHER_BRICK_FENCE, MaterialKey.from(113, 0))
        register(Material.NETHER_BRICK_STAIRS, MaterialKey.from(114, 0))
        register(Material.ENCHANTING_TABLE, MaterialKey.from(116, 0))
        register(Material.END_PORTAL_FRAME, MaterialKey.from(120, 0))
        register(Material.END_STONE, MaterialKey.from(121, 0))
        register(Material.DRAGON_EGG, MaterialKey.from(122, 0))
        register(Material.REDSTONE_LAMP, MaterialKey.from(123, 0))
        register(Material.OAK_SLAB, MaterialKey.from(126, 0))
        register(Material.SPRUCE_SLAB, MaterialKey.from(126, 1))
        register(Material.BIRCH_SLAB, MaterialKey.from(126, 2))
        register(Material.JUNGLE_SLAB, MaterialKey.from(126, 3))
        register(Material.ACACIA_SLAB, MaterialKey.from(126, 4))
        register(Material.DARK_OAK_SLAB, MaterialKey.from(126, 5))
        register(Material.SANDSTONE_STAIRS, MaterialKey.from(128, 0))
        register(Material.EMERALD_ORE, MaterialKey.from(129, 0))
        register(Material.ENDER_CHEST, MaterialKey.from(130, 0))
        register(Material.TRIPWIRE_HOOK, MaterialKey.from(131, 0))
        register(Material.EMERALD_BLOCK, MaterialKey.from(133, 0))
        register(Material.SPRUCE_STAIRS, MaterialKey.from(134, 0))
        register(Material.BIRCH_STAIRS, MaterialKey.from(135, 0))
        register(Material.JUNGLE_STAIRS, MaterialKey.from(136, 0))
        register(Material.COMMAND_BLOCK, MaterialKey.from(137, 0))
        register(Material.BEACON, MaterialKey.from(138, 0))
        register(Material.COBBLESTONE_WALL, MaterialKey.from(139, 0))
        register(Material.MOSSY_COBBLESTONE_WALL, MaterialKey.from(139, 1))
        register(Material.OAK_BUTTON, MaterialKey.from(143, 0))
        register(Material.ANVIL, MaterialKey.from(145, 0))
        register(Material.TRAPPED_CHEST, MaterialKey.from(146, 0))
        register(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, MaterialKey.from(147, 0))
        register(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, MaterialKey.from(148, 0))
        register(Material.DAYLIGHT_DETECTOR, MaterialKey.from(151, 0))
        register(Material.REDSTONE_BLOCK, MaterialKey.from(152, 0))
        register(Material.NETHER_QUARTZ_ORE, MaterialKey.from(153, 0))
        register(Material.HOPPER, MaterialKey.from(154, 0))
        register(Material.QUARTZ_BLOCK, MaterialKey.from(155, 0))
        register(Material.CHISELED_QUARTZ_BLOCK, MaterialKey.from(155, 1))
        register(Material.QUARTZ_PILLAR, MaterialKey.from(155, 2))
        register(Material.QUARTZ_STAIRS, MaterialKey.from(156, 0))
        register(Material.ACTIVATOR_RAIL, MaterialKey.from(157, 0))
        register(Material.DROPPER, MaterialKey.from(158, 0))
        register(Material.WHITE_TERRACOTTA, MaterialKey.from(159, 0))
        register(Material.ORANGE_TERRACOTTA, MaterialKey.from(159, 1))
        register(Material.MAGENTA_TERRACOTTA, MaterialKey.from(159, 2))
        register(Material.LIGHT_BLUE_TERRACOTTA, MaterialKey.from(159, 3))
        register(Material.YELLOW_TERRACOTTA, MaterialKey.from(159, 4))
        register(Material.LIME_TERRACOTTA, MaterialKey.from(159, 5))
        register(Material.PINK_TERRACOTTA, MaterialKey.from(159, 6))
        register(Material.GRAY_TERRACOTTA, MaterialKey.from(159, 7))
        register(Material.LIGHT_GRAY_TERRACOTTA, MaterialKey.from(159, 8))
        register(Material.CYAN_TERRACOTTA, MaterialKey.from(159, 9))
        register(Material.PURPLE_TERRACOTTA, MaterialKey.from(159, 10))
        register(Material.BLUE_TERRACOTTA, MaterialKey.from(159, 11))
        register(Material.BROWN_TERRACOTTA, MaterialKey.from(159, 12))
        register(Material.GREEN_TERRACOTTA, MaterialKey.from(159, 13))
        register(Material.RED_TERRACOTTA, MaterialKey.from(159, 14))
        register(Material.BLACK_TERRACOTTA, MaterialKey.from(159, 15))
        register(Material.WHITE_STAINED_GLASS_PANE, MaterialKey.from(160, 0))
        register(Material.ORANGE_STAINED_GLASS_PANE, MaterialKey.from(160, 1))
        register(Material.MAGENTA_STAINED_GLASS_PANE, MaterialKey.from(160, 2))
        register(Material.LIGHT_BLUE_STAINED_GLASS_PANE, MaterialKey.from(160, 3))
        register(Material.YELLOW_STAINED_GLASS_PANE, MaterialKey.from(160, 4))
        register(Material.LIME_STAINED_GLASS_PANE, MaterialKey.from(160, 5))
        register(Material.PINK_STAINED_GLASS_PANE, MaterialKey.from(160, 6))
        register(Material.GRAY_STAINED_GLASS_PANE, MaterialKey.from(160, 7))
        register(Material.LIGHT_GRAY_STAINED_GLASS_PANE, MaterialKey.from(160, 8))
        register(Material.CYAN_STAINED_GLASS_PANE, MaterialKey.from(160, 9))
        register(Material.PURPLE_STAINED_GLASS_PANE, MaterialKey.from(160, 10))
        register(Material.BLUE_STAINED_GLASS_PANE, MaterialKey.from(160, 11))
        register(Material.BROWN_STAINED_GLASS_PANE, MaterialKey.from(160, 12))
        register(Material.GREEN_STAINED_GLASS_PANE, MaterialKey.from(160, 13))
        register(Material.RED_STAINED_GLASS_PANE, MaterialKey.from(160, 14))
        register(Material.BLACK_STAINED_GLASS_PANE, MaterialKey.from(160, 15))
        register(Material.ACACIA_LEAVES, MaterialKey.from(161, 0))
        register(Material.DARK_OAK_LEAVES, MaterialKey.from(161, 1))
        register(Material.ACACIA_WOOD, MaterialKey.from(162, 0))
        register(Material.DARK_OAK_WOOD, MaterialKey.from(162, 1))
        register(Material.ACACIA_STAIRS, MaterialKey.from(163, 0))
        register(Material.DARK_OAK_STAIRS, MaterialKey.from(164, 0))
        register(Material.SLIME_BLOCK, MaterialKey.from(165, 0))
        register(Material.BARRIER, MaterialKey.from(166, 0))
        register(Material.IRON_TRAPDOOR, MaterialKey.from(167, 0))
        register(Material.PRISMARINE, MaterialKey.from(168, 0))
        register(Material.PRISMARINE_BRICKS, MaterialKey.from(168, 1))
        register(Material.DARK_PRISMARINE, MaterialKey.from(168, 2))
        register(Material.SEA_LANTERN, MaterialKey.from(169, 0))
        register(Material.HAY_BLOCK, MaterialKey.from(170, 0))
        register(Material.WHITE_CARPET, MaterialKey.from(171, 0))
        register(Material.ORANGE_CARPET, MaterialKey.from(171, 1))
        register(Material.MAGENTA_CARPET, MaterialKey.from(171, 2))
        register(Material.LIGHT_BLUE_CARPET, MaterialKey.from(171, 3))
        register(Material.YELLOW_CARPET, MaterialKey.from(171, 4))
        register(Material.LIME_CARPET, MaterialKey.from(171, 5))
        register(Material.PINK_CARPET, MaterialKey.from(171, 6))
        register(Material.GRAY_CARPET, MaterialKey.from(171, 7))
        register(Material.LIGHT_GRAY_CARPET, MaterialKey.from(171, 8))
        register(Material.CYAN_CARPET, MaterialKey.from(171, 9))
        register(Material.PURPLE_CARPET, MaterialKey.from(171, 10))
        register(Material.BLUE_CARPET, MaterialKey.from(171, 11))
        register(Material.BROWN_CARPET, MaterialKey.from(171, 12))
        register(Material.GREEN_CARPET, MaterialKey.from(171, 13))
        register(Material.RED_CARPET, MaterialKey.from(171, 14))
        register(Material.BLACK_CARPET, MaterialKey.from(171, 15))
        register(Material.TERRACOTTA, MaterialKey.from(172, 0))
        register(Material.COAL_BLOCK, MaterialKey.from(173, 0))
        register(Material.PACKED_ICE, MaterialKey.from(174, 0))
        register(Material.SUNFLOWER, MaterialKey.from(175, 0))
        register(Material.LILAC, MaterialKey.from(175, 1))
        register(Material.TALL_GRASS, MaterialKey.from(175, 2))
        register(Material.LARGE_FERN, MaterialKey.from(175, 3))
        register(Material.ROSE_BUSH, MaterialKey.from(175, 4))
        register(Material.CHISELED_RED_SANDSTONE, MaterialKey.from(179, 1))
        register(Material.SMOOTH_RED_SANDSTONE, MaterialKey.from(179, 2))
        register(Material.RED_SANDSTONE_STAIRS, MaterialKey.from(180, 0))
        register(Material.RED_SANDSTONE_SLAB, MaterialKey.from(182, 0))
        register(Material.SPRUCE_FENCE_GATE, MaterialKey.from(183, 0))
        register(Material.BIRCH_FENCE_GATE, MaterialKey.from(184, 0))
        register(Material.JUNGLE_FENCE_GATE, MaterialKey.from(185, 0))
        register(Material.DARK_OAK_FENCE_GATE, MaterialKey.from(186, 0))
        register(Material.ACACIA_FENCE_GATE, MaterialKey.from(187, 0))
        register(Material.SPRUCE_FENCE, MaterialKey.from(188, 0))
        register(Material.BIRCH_FENCE, MaterialKey.from(189, 0))
        register(Material.JUNGLE_FENCE, MaterialKey.from(190, 0))
        register(Material.DARK_OAK_FENCE, MaterialKey.from(191, 0))
        register(Material.ACACIA_FENCE, MaterialKey.from(192, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_SHOVEL, MaterialKey.from(256, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_PICKAXE, MaterialKey.from(257, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_AXE, MaterialKey.from(258, 0))
        register(MaterialWrapperContext.ITEM, Material.FLINT_AND_STEEL, MaterialKey.from(259, 0))
        register(MaterialWrapperContext.ITEM, Material.APPLE, MaterialKey.from(260, 0))
        register(MaterialWrapperContext.ITEM, Material.BOW, MaterialKey.from(261, 0))
        register(MaterialWrapperContext.ITEM, Material.ARROW, MaterialKey.from(262, 0))
        register(MaterialWrapperContext.ITEM, Material.COAL, MaterialKey.from(263, 0))
        register(MaterialWrapperContext.ITEM, Material.CHARCOAL, MaterialKey.from(263, 1))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND, MaterialKey.from(264, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_INGOT, MaterialKey.from(265, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLD_INGOT, MaterialKey.from(266, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_SWORD, MaterialKey.from(267, 0))
        register(MaterialWrapperContext.ITEM, Material.WOODEN_SWORD, MaterialKey.from(268, 0))
        register(MaterialWrapperContext.ITEM, Material.WOODEN_SHOVEL, MaterialKey.from(269, 0))
        register(MaterialWrapperContext.ITEM, Material.WOODEN_PICKAXE, MaterialKey.from(270, 0))
        register(MaterialWrapperContext.ITEM, Material.WOODEN_AXE, MaterialKey.from(271, 0))
        register(MaterialWrapperContext.ITEM, Material.STONE_SWORD, MaterialKey.from(272, 0))
        register(MaterialWrapperContext.ITEM, Material.STONE_SHOVEL, MaterialKey.from(273, 0))
        register(MaterialWrapperContext.ITEM, Material.STONE_PICKAXE, MaterialKey.from(274, 0))
        register(MaterialWrapperContext.ITEM, Material.STONE_AXE, MaterialKey.from(275, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_SWORD, MaterialKey.from(276, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_SHOVEL, MaterialKey.from(277, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_PICKAXE, MaterialKey.from(278, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_AXE, MaterialKey.from(279, 0))
        register(MaterialWrapperContext.ITEM, Material.STICK, MaterialKey.from(280, 0))
        register(MaterialWrapperContext.ITEM, Material.BOWL, MaterialKey.from(281, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSHROOM_STEW, MaterialKey.from(282, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_SWORD, MaterialKey.from(283, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_SHOVEL, MaterialKey.from(284, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_PICKAXE, MaterialKey.from(285, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_AXE, MaterialKey.from(286, 0))
        register(MaterialWrapperContext.ITEM, Material.STRING, MaterialKey.from(287, 0))
        register(MaterialWrapperContext.ITEM, Material.FEATHER, MaterialKey.from(288, 0))
        register(MaterialWrapperContext.ITEM, Material.GUNPOWDER, MaterialKey.from(289, 0))
        register(MaterialWrapperContext.ITEM, Material.WOODEN_HOE, MaterialKey.from(290, 0))
        register(MaterialWrapperContext.ITEM, Material.STONE_HOE, MaterialKey.from(291, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_HOE, MaterialKey.from(292, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_HOE, MaterialKey.from(293, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_HOE, MaterialKey.from(294, 0))
        register(MaterialWrapperContext.ITEM, Material.WHEAT_SEEDS, MaterialKey.from(295, 0))
        register(MaterialWrapperContext.ITEM, Material.WHEAT, MaterialKey.from(296, 0))
        register(MaterialWrapperContext.ITEM, Material.BREAD, MaterialKey.from(297, 0))
        register(MaterialWrapperContext.ITEM, Material.LEATHER_HELMET, MaterialKey.from(298, 0))
        register(MaterialWrapperContext.ITEM, Material.LEATHER_CHESTPLATE, MaterialKey.from(299, 0))
        register(MaterialWrapperContext.ITEM, Material.LEATHER_LEGGINGS, MaterialKey.from(300, 0))
        register(MaterialWrapperContext.ITEM, Material.LEATHER_BOOTS, MaterialKey.from(301, 0))
        register(MaterialWrapperContext.ITEM, Material.CHAINMAIL_HELMET, MaterialKey.from(302, 0))
        register(MaterialWrapperContext.ITEM, Material.CHAINMAIL_CHESTPLATE, MaterialKey.from(303, 0))
        register(MaterialWrapperContext.ITEM, Material.CHAINMAIL_LEGGINGS, MaterialKey.from(304, 0))
        register(MaterialWrapperContext.ITEM, Material.CHAINMAIL_BOOTS, MaterialKey.from(305, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_HELMET, MaterialKey.from(306, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_CHESTPLATE, MaterialKey.from(307, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_LEGGINGS, MaterialKey.from(308, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_BOOTS, MaterialKey.from(309, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_HELMET, MaterialKey.from(310, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_CHESTPLATE, MaterialKey.from(311, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_LEGGINGS, MaterialKey.from(312, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_BOOTS, MaterialKey.from(313, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_HELMET, MaterialKey.from(314, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_CHESTPLATE, MaterialKey.from(315, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_LEGGINGS, MaterialKey.from(316, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_BOOTS, MaterialKey.from(317, 0))
        register(MaterialWrapperContext.ITEM, Material.FLINT, MaterialKey.from(318, 0))
        register(MaterialWrapperContext.ITEM, Material.PORKCHOP, MaterialKey.from(319, 0))
        register(MaterialWrapperContext.ITEM, Material.COOKED_PORKCHOP, MaterialKey.from(320, 0))
        register(MaterialWrapperContext.ITEM, Material.PAINTING, MaterialKey.from(321, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_APPLE, MaterialKey.from(322, 0))
        register(MaterialWrapperContext.ITEM, Material.ENCHANTED_GOLDEN_APPLE, MaterialKey.from(322, 1))
        register(MaterialWrapperContext.ITEM, Material.OAK_SIGN, MaterialKey.from(323, 0))
        register(MaterialWrapperContext.ITEM, Material.OAK_DOOR, MaterialKey.from(324, 0))
        register(MaterialWrapperContext.ITEM, Material.BUCKET, MaterialKey.from(325, 0))
        register(MaterialWrapperContext.ITEM, Material.WATER_BUCKET, MaterialKey.from(326, 0))
        register(MaterialWrapperContext.ITEM, Material.LAVA_BUCKET, MaterialKey.from(327, 0))
        register(MaterialWrapperContext.ITEM, Material.MINECART, MaterialKey.from(328, 0))
        register(MaterialWrapperContext.ITEM, Material.SADDLE, MaterialKey.from(329, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_DOOR, MaterialKey.from(330, 0))
        register(MaterialWrapperContext.ITEM, Material.REDSTONE_WIRE, MaterialKey.from(331, 0))
        register(MaterialWrapperContext.ITEM, Material.SNOWBALL, MaterialKey.from(332, 0))
        register(MaterialWrapperContext.ITEM, Material.OAK_BOAT, MaterialKey.from(333, 0))
        register(MaterialWrapperContext.ITEM, Material.LEATHER, MaterialKey.from(334, 0))
        register(MaterialWrapperContext.ITEM, Material.MILK_BUCKET, MaterialKey.from(335, 0))
        register(MaterialWrapperContext.ITEM, Material.BRICK, MaterialKey.from(336, 0))
        register(MaterialWrapperContext.ITEM, Material.CLAY_BALL, MaterialKey.from(337, 0))
        register(MaterialWrapperContext.ITEM, Material.SUGAR_CANE, MaterialKey.from(338, 0))
        register(MaterialWrapperContext.ITEM, Material.PAPER, MaterialKey.from(339, 0))
        register(MaterialWrapperContext.ITEM, Material.BOOK, MaterialKey.from(340, 0))
        register(MaterialWrapperContext.ITEM, Material.SLIME_BALL, MaterialKey.from(341, 0))
        register(MaterialWrapperContext.ITEM, Material.CHEST_MINECART, MaterialKey.from(342, 0))
        register(MaterialWrapperContext.ITEM, Material.FURNACE_MINECART, MaterialKey.from(343, 0))
        register(MaterialWrapperContext.ITEM, Material.EGG, MaterialKey.from(344, 0))
        register(MaterialWrapperContext.ITEM, Material.COMPASS, MaterialKey.from(345, 0))
        register(MaterialWrapperContext.ITEM, Material.FISHING_ROD, MaterialKey.from(346, 0))
        register(MaterialWrapperContext.ITEM, Material.CLOCK, MaterialKey.from(347, 0))
        register(MaterialWrapperContext.ITEM, Material.GLOWSTONE_DUST, MaterialKey.from(348, 0))
        register(MaterialWrapperContext.ITEM, Material.PUFFERFISH, MaterialKey.from(349, 3))
        register(MaterialWrapperContext.ITEM, Material.INK_SAC, MaterialKey.from(351, 0))
        register(MaterialWrapperContext.ITEM, Material.RED_DYE, MaterialKey.from(351, 1))
        register(MaterialWrapperContext.ITEM, Material.GREEN_DYE, MaterialKey.from(351, 2))
        register(MaterialWrapperContext.ITEM, Material.COCOA_BEANS, MaterialKey.from(351, 3))
        register(MaterialWrapperContext.ITEM, Material.LAPIS_LAZULI, MaterialKey.from(351, 4))
        register(MaterialWrapperContext.ITEM, Material.PURPLE_DYE, MaterialKey.from(351, 5))
        register(MaterialWrapperContext.ITEM, Material.CYAN_DYE, MaterialKey.from(351, 6))
        register(MaterialWrapperContext.ITEM, Material.LIGHT_GRAY_DYE, MaterialKey.from(351, 7))
        register(MaterialWrapperContext.ITEM, Material.GRAY_DYE, MaterialKey.from(351, 8))
        register(MaterialWrapperContext.ITEM, Material.PINK_DYE, MaterialKey.from(351, 9))
        register(MaterialWrapperContext.ITEM, Material.LIME_DYE, MaterialKey.from(351, 10))
        register(MaterialWrapperContext.ITEM, Material.YELLOW_DYE, MaterialKey.from(351, 11))
        register(MaterialWrapperContext.ITEM, Material.LIGHT_BLUE_DYE, MaterialKey.from(351, 12))
        register(MaterialWrapperContext.ITEM, Material.MAGENTA_DYE, MaterialKey.from(351, 13))
        register(MaterialWrapperContext.ITEM, Material.ORANGE_DYE, MaterialKey.from(351, 14))
        register(MaterialWrapperContext.ITEM, Material.BONE_MEAL, MaterialKey.from(351, 15))
        register(MaterialWrapperContext.ITEM, Material.BONE, MaterialKey.from(352, 0))
        register(MaterialWrapperContext.ITEM, Material.SUGAR, MaterialKey.from(353, 0))
        register(MaterialWrapperContext.ITEM, Material.CAKE, MaterialKey.from(354, 0))
        register(MaterialWrapperContext.ITEM, Material.RED_BED, MaterialKey.from(355, 0))
        register(MaterialWrapperContext.ITEM, Material.REPEATER, MaterialKey.from(356, 0))
        register(MaterialWrapperContext.ITEM, Material.COOKIE, MaterialKey.from(357, 0))
        register(MaterialWrapperContext.ITEM, Material.FILLED_MAP, MaterialKey.from(358, 0))
        register(MaterialWrapperContext.ITEM, Material.SHEARS, MaterialKey.from(359, 0))
        register(MaterialWrapperContext.ITEM, Material.MELON_SLICE, MaterialKey.from(360, 0))
        register(MaterialWrapperContext.ITEM, Material.PUMPKIN_SEEDS, MaterialKey.from(361, 0))
        register(MaterialWrapperContext.ITEM, Material.MELON_SEEDS, MaterialKey.from(362, 0))
        register(MaterialWrapperContext.ITEM, Material.BEEF, MaterialKey.from(363, 0))
        register(MaterialWrapperContext.ITEM, Material.COOKED_BEEF, MaterialKey.from(364, 0))
        register(MaterialWrapperContext.ITEM, Material.CHICKEN, MaterialKey.from(365, 0))
        register(MaterialWrapperContext.ITEM, Material.COOKED_CHICKEN, MaterialKey.from(366, 0))
        register(MaterialWrapperContext.ITEM, Material.ROTTEN_FLESH, MaterialKey.from(367, 0))
        register(MaterialWrapperContext.ITEM, Material.ENDER_PEARL, MaterialKey.from(368, 0))
        register(MaterialWrapperContext.ITEM, Material.BLAZE_ROD, MaterialKey.from(369, 0))
        register(MaterialWrapperContext.ITEM, Material.GHAST_TEAR, MaterialKey.from(370, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLD_NUGGET, MaterialKey.from(371, 0))
        register(MaterialWrapperContext.ITEM, Material.NETHER_WART, MaterialKey.from(372, 0))
        register(MaterialWrapperContext.ITEM, Material.POTION, MaterialKey.from(373, 0))
        register(MaterialWrapperContext.ITEM, Material.GLASS_BOTTLE, MaterialKey.from(374, 0))
        register(MaterialWrapperContext.ITEM, Material.SPIDER_EYE, MaterialKey.from(375, 0))
        register(MaterialWrapperContext.ITEM, Material.FERMENTED_SPIDER_EYE, MaterialKey.from(376, 0))
        register(MaterialWrapperContext.ITEM, Material.BLAZE_POWDER, MaterialKey.from(377, 0))
        register(MaterialWrapperContext.ITEM, Material.MAGMA_CREAM, MaterialKey.from(378, 0))
        register(MaterialWrapperContext.ITEM, Material.BREWING_STAND, MaterialKey.from(379, 0))
        register(MaterialWrapperContext.ITEM, Material.CAULDRON, MaterialKey.from(380, 0))
        register(MaterialWrapperContext.ITEM, Material.ENDER_EYE, MaterialKey.from(381, 0))
        register(MaterialWrapperContext.ITEM, Material.GLISTERING_MELON_SLICE, MaterialKey.from(382, 0))
        register(MaterialWrapperContext.ITEM, Material.CREEPER_SPAWN_EGG, MaterialKey.from(383, 50))
        register(MaterialWrapperContext.ITEM, Material.SKELETON_SPAWN_EGG, MaterialKey.from(383, 51))
        register(MaterialWrapperContext.ITEM, Material.SPIDER_SPAWN_EGG, MaterialKey.from(383, 52))
        register(MaterialWrapperContext.ITEM, Material.ZOMBIE_SPAWN_EGG, MaterialKey.from(383, 54))
        register(MaterialWrapperContext.ITEM, Material.SLIME_SPAWN_EGG, MaterialKey.from(383, 55))
        register(MaterialWrapperContext.ITEM, Material.GHAST_SPAWN_EGG, MaterialKey.from(383, 56))
        register(MaterialWrapperContext.ITEM, Material.ZOMBIFIED_PIGLIN_SPAWN_EGG, MaterialKey.from(383, 57))
        register(MaterialWrapperContext.ITEM, Material.ENDERMAN_SPAWN_EGG, MaterialKey.from(383, 58))
        register(MaterialWrapperContext.ITEM, Material.CAVE_SPIDER_SPAWN_EGG, MaterialKey.from(383, 59))
        register(MaterialWrapperContext.ITEM, Material.SILVERFISH_SPAWN_EGG, MaterialKey.from(383, 60))
        register(MaterialWrapperContext.ITEM, Material.BLAZE_SPAWN_EGG, MaterialKey.from(383, 61))
        register(MaterialWrapperContext.ITEM, Material.MAGMA_CUBE_SPAWN_EGG, MaterialKey.from(383, 62))
        register(MaterialWrapperContext.ITEM, Material.BAT_SPAWN_EGG, MaterialKey.from(383, 65))
        register(MaterialWrapperContext.ITEM, Material.WITCH_SPAWN_EGG, MaterialKey.from(383, 66))
        register(MaterialWrapperContext.ITEM, Material.ENDERMITE_SPAWN_EGG, MaterialKey.from(383, 67))
        register(MaterialWrapperContext.ITEM, Material.GUARDIAN_SPAWN_EGG, MaterialKey.from(383, 68))
        register(MaterialWrapperContext.ITEM, Material.PIG_SPAWN_EGG, MaterialKey.from(383, 90))
        register(MaterialWrapperContext.ITEM, Material.SHEEP_SPAWN_EGG, MaterialKey.from(383, 91))
        register(MaterialWrapperContext.ITEM, Material.COW_SPAWN_EGG, MaterialKey.from(383, 92))
        register(MaterialWrapperContext.ITEM, Material.CHICKEN_SPAWN_EGG, MaterialKey.from(383, 93))
        register(MaterialWrapperContext.ITEM, Material.SQUID_SPAWN_EGG, MaterialKey.from(383, 94))
        register(MaterialWrapperContext.ITEM, Material.WOLF_SPAWN_EGG, MaterialKey.from(383, 95))
        register(MaterialWrapperContext.ITEM, Material.MOOSHROOM_SPAWN_EGG, MaterialKey.from(383, 96))
        register(MaterialWrapperContext.ITEM, Material.OCELOT_SPAWN_EGG, MaterialKey.from(383, 98))
        register(MaterialWrapperContext.ITEM, Material.HORSE_SPAWN_EGG, MaterialKey.from(383, 100))
        register(MaterialWrapperContext.ITEM, Material.RABBIT_SPAWN_EGG, MaterialKey.from(383, 101))
        register(MaterialWrapperContext.ITEM, Material.VILLAGER_SPAWN_EGG, MaterialKey.from(383, 120))
        register(MaterialWrapperContext.ITEM, Material.EXPERIENCE_BOTTLE, MaterialKey.from(384, 0))
        register(MaterialWrapperContext.ITEM, Material.FIRE_CHARGE, MaterialKey.from(385, 0))
        register(MaterialWrapperContext.ITEM, Material.WRITABLE_BOOK, MaterialKey.from(386, 0))
        register(MaterialWrapperContext.ITEM, Material.WRITTEN_BOOK, MaterialKey.from(387, 0))
        register(MaterialWrapperContext.ITEM, Material.EMERALD, MaterialKey.from(388, 0))
        register(MaterialWrapperContext.ITEM, Material.ITEM_FRAME, MaterialKey.from(389, 0))
        register(MaterialWrapperContext.ITEM, Material.FLOWER_POT, MaterialKey.from(390, 0))
        register(MaterialWrapperContext.ITEM, Material.POTTED_POPPY, MaterialKey.from(390, 1))
        register(MaterialWrapperContext.ITEM, Material.POTTED_DANDELION, MaterialKey.from(390, 2))
        register(MaterialWrapperContext.ITEM, Material.POTTED_OAK_SAPLING, MaterialKey.from(390, 3))
        register(MaterialWrapperContext.ITEM, Material.POTTED_SPRUCE_SAPLING, MaterialKey.from(390, 4))
        register(MaterialWrapperContext.ITEM, Material.POTTED_BIRCH_SAPLING, MaterialKey.from(390, 5))
        register(MaterialWrapperContext.ITEM, Material.POTTED_JUNGLE_SAPLING, MaterialKey.from(390, 6))
        register(MaterialWrapperContext.ITEM, Material.POTTED_RED_MUSHROOM, MaterialKey.from(390, 7))
        register(MaterialWrapperContext.ITEM, Material.POTTED_BROWN_MUSHROOM, MaterialKey.from(390, 8))
        register(MaterialWrapperContext.ITEM, Material.POTTED_CACTUS, MaterialKey.from(390, 9))
        register(MaterialWrapperContext.ITEM, Material.POTTED_DEAD_BUSH, MaterialKey.from(390, 10))
        register(MaterialWrapperContext.ITEM, Material.POTTED_FERN, MaterialKey.from(390, 11))
        register(MaterialWrapperContext.ITEM, Material.POTTED_ACACIA_SAPLING, MaterialKey.from(390, 12))
        register(MaterialWrapperContext.ITEM, Material.POTTED_DARK_OAK_SAPLING, MaterialKey.from(390, 13))
        register(MaterialWrapperContext.ITEM, Material.CARROT, MaterialKey.from(391, 0))
        register(MaterialWrapperContext.ITEM, Material.POTATO, MaterialKey.from(392, 0))
        register(MaterialWrapperContext.ITEM, Material.BAKED_POTATO, MaterialKey.from(393, 0))
        register(MaterialWrapperContext.ITEM, Material.POISONOUS_POTATO, MaterialKey.from(394, 0))
        register(MaterialWrapperContext.ITEM, Material.MAP, MaterialKey.from(395, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_CARROT, MaterialKey.from(396, 0))
        register(MaterialWrapperContext.ITEM, Material.SKELETON_SKULL, MaterialKey.from(397, 0))
        register(MaterialWrapperContext.ITEM, Material.WITHER_SKELETON_SKULL, MaterialKey.from(397, 1))
        register(MaterialWrapperContext.ITEM, Material.ZOMBIE_HEAD, MaterialKey.from(397, 2))
        register(MaterialWrapperContext.ITEM, Material.PLAYER_HEAD, MaterialKey.from(397, 3))
        register(MaterialWrapperContext.ITEM, Material.CREEPER_HEAD, MaterialKey.from(397, 4))
        register(MaterialWrapperContext.ITEM, Material.CARROT_ON_A_STICK, MaterialKey.from(398, 0))
        register(MaterialWrapperContext.ITEM, Material.NETHER_STAR, MaterialKey.from(399, 0))
        register(MaterialWrapperContext.ITEM, Material.PUMPKIN_PIE, MaterialKey.from(400, 0))
        register(MaterialWrapperContext.ITEM, Material.ENCHANTED_BOOK, MaterialKey.from(403, 0))
        register(MaterialWrapperContext.ITEM, Material.COMPARATOR, MaterialKey.from(404, 0))
        register(MaterialWrapperContext.ITEM, Material.QUARTZ, MaterialKey.from(406, 0))
        register(MaterialWrapperContext.ITEM, Material.TNT_MINECART, MaterialKey.from(407, 0))
        register(MaterialWrapperContext.ITEM, Material.HOPPER_MINECART, MaterialKey.from(408, 0))
        register(MaterialWrapperContext.ITEM, Material.PRISMARINE_SHARD, MaterialKey.from(409, 0))
        register(MaterialWrapperContext.ITEM, Material.PRISMARINE_CRYSTALS, MaterialKey.from(410, 0))
        register(MaterialWrapperContext.ITEM, Material.RABBIT, MaterialKey.from(411, 0))
        register(MaterialWrapperContext.ITEM, Material.COOKED_RABBIT, MaterialKey.from(412, 0))
        register(MaterialWrapperContext.ITEM, Material.RABBIT_STEW, MaterialKey.from(413, 0))
        register(MaterialWrapperContext.ITEM, Material.RABBIT_FOOT, MaterialKey.from(414, 0))
        register(MaterialWrapperContext.ITEM, Material.RABBIT_HIDE, MaterialKey.from(415, 0))
        register(MaterialWrapperContext.ITEM, Material.ARMOR_STAND, MaterialKey.from(416, 0))
        register(MaterialWrapperContext.ITEM, Material.IRON_HORSE_ARMOR, MaterialKey.from(417, 0))
        register(MaterialWrapperContext.ITEM, Material.GOLDEN_HORSE_ARMOR, MaterialKey.from(418, 0))
        register(MaterialWrapperContext.ITEM, Material.DIAMOND_HORSE_ARMOR, MaterialKey.from(419, 0))
        register(MaterialWrapperContext.ITEM, Material.LEAD, MaterialKey.from(420, 0))
        register(MaterialWrapperContext.ITEM, Material.NAME_TAG, MaterialKey.from(421, 0))
        register(MaterialWrapperContext.ITEM, Material.COMMAND_BLOCK_MINECART, MaterialKey.from(422, 0))
        register(MaterialWrapperContext.ITEM, Material.MUTTON, MaterialKey.from(423, 0))
        register(MaterialWrapperContext.ITEM, Material.COOKED_MUTTON, MaterialKey.from(424, 0))
        register(MaterialWrapperContext.ITEM, Material.SPRUCE_DOOR, MaterialKey.from(427, 0))
        register(MaterialWrapperContext.ITEM, Material.BIRCH_DOOR, MaterialKey.from(428, 0))
        register(MaterialWrapperContext.ITEM, Material.JUNGLE_DOOR, MaterialKey.from(429, 0))
        register(MaterialWrapperContext.ITEM, Material.ACACIA_DOOR, MaterialKey.from(430, 0))
        register(MaterialWrapperContext.ITEM, Material.DARK_OAK_DOOR, MaterialKey.from(431, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_13, MaterialKey.from(2256, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_CAT, MaterialKey.from(2257, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_BLOCKS, MaterialKey.from(2258, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_CHIRP, MaterialKey.from(2259, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_FAR, MaterialKey.from(2260, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_MALL, MaterialKey.from(2261, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_MELLOHI, MaterialKey.from(2262, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_STAL, MaterialKey.from(2263, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_STRAD, MaterialKey.from(2264, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_WARD, MaterialKey.from(2265, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_11, MaterialKey.from(2266, 0))
        register(MaterialWrapperContext.ITEM, Material.MUSIC_DISC_WAIT, MaterialKey.from(2267, 0))
        register(MaterialWrapperContext.BLOCK, Material.AIR, MaterialKey.from(0, 0))
        register(MaterialWrapperContext.BLOCK, Material.WATER, MaterialKey.from(9, 0))
        register(MaterialWrapperContext.BLOCK, Material.LAVA, MaterialKey.from(11, 0))
        register(MaterialWrapperContext.BLOCK, Material.RED_BED, MaterialKey.from(26, 0))
        register(MaterialWrapperContext.BLOCK, Material.PISTON_HEAD, MaterialKey.from(34, 0))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_STONE_SLAB, MaterialKey.from(43, 0))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_SANDSTONE_SLAB, MaterialKey.from(43, 1))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_COBBLESTONE_SLAB, MaterialKey.from(43, 3))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_STONE_BRICK_SLAB, MaterialKey.from(43, 5))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_NETHER_BRICK_SLAB, MaterialKey.from(43, 6))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_QUARTZ_SLAB, MaterialKey.from(43, 7))
        register(MaterialWrapperContext.BLOCK, Material.SMOOTH_DOUBLE_STONE_SLAB, MaterialKey.from(43, 8))
        register(MaterialWrapperContext.BLOCK, Material.FIRE, MaterialKey.from(51, 0))
        register(MaterialWrapperContext.BLOCK, Material.REDSTONE_WIRE, MaterialKey.from(55, 0))
        register(MaterialWrapperContext.BLOCK, Material.WHEAT, MaterialKey.from(59, 0))
        register(MaterialWrapperContext.BLOCK, Material.OAK_SIGN, MaterialKey.from(63, 0))
        register(MaterialWrapperContext.BLOCK, Material.OAK_DOOR, MaterialKey.from(64, 0))
        register(MaterialWrapperContext.BLOCK, Material.OAK_WALL_SIGN, MaterialKey.from(68, 0))
        register(MaterialWrapperContext.BLOCK, Material.IRON_DOOR, MaterialKey.from(71, 0))
        register(MaterialWrapperContext.BLOCK, Material.SUGAR_CANE, MaterialKey.from(83, 0))
        register(MaterialWrapperContext.BLOCK, Material.CAKE, MaterialKey.from(92, 0))
        register(MaterialWrapperContext.BLOCK, Material.REPEATER, MaterialKey.from(93, 0))
        register(MaterialWrapperContext.BLOCK, Material.PUMPKIN_STEM, MaterialKey.from(104, 0))
        register(MaterialWrapperContext.BLOCK, Material.MELON_STEM, MaterialKey.from(105, 0))
        register(MaterialWrapperContext.BLOCK, Material.NETHER_WART, MaterialKey.from(115, 0))
        register(MaterialWrapperContext.BLOCK, Material.BREWING_STAND, MaterialKey.from(117, 0))
        register(MaterialWrapperContext.BLOCK, Material.CAULDRON, MaterialKey.from(118, 0))
        register(MaterialWrapperContext.BLOCK, Material.END_PORTAL, MaterialKey.from(119, 0))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_OAK_SLAB, MaterialKey.from(125, 0))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_SPRUCE_SLAB, MaterialKey.from(125, 1))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_BIRCH_SLAB, MaterialKey.from(125, 2))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_JUNGLE_SLAB, MaterialKey.from(125, 3))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_ACACIA_SLAB, MaterialKey.from(125, 4))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_DARK_OAK_SLAB, MaterialKey.from(125, 5))
        register(MaterialWrapperContext.BLOCK, Material.COCOA, MaterialKey.from(127, 0))
        register(MaterialWrapperContext.BLOCK, Material.TRIPWIRE, MaterialKey.from(132, 0))
        register(MaterialWrapperContext.BLOCK, Material.FLOWER_POT, MaterialKey.from(140, 0))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_POPPY, MaterialKey.from(140, 1))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_DANDELION, MaterialKey.from(140, 2))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_OAK_SAPLING, MaterialKey.from(140, 3))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_SPRUCE_SAPLING, MaterialKey.from(140, 4))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_BIRCH_SAPLING, MaterialKey.from(140, 5))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_JUNGLE_SAPLING, MaterialKey.from(140, 6))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_RED_MUSHROOM, MaterialKey.from(140, 7))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_BROWN_MUSHROOM, MaterialKey.from(140, 8))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_CACTUS, MaterialKey.from(140, 9))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_DEAD_BUSH, MaterialKey.from(140, 10))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_FERN, MaterialKey.from(140, 11))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_ACACIA_SAPLING, MaterialKey.from(140, 12))
        register(MaterialWrapperContext.BLOCK, Material.POTTED_DARK_OAK_SAPLING, MaterialKey.from(140, 13))
        register(MaterialWrapperContext.BLOCK, Material.CARROTS, MaterialKey.from(141, 0))
        register(MaterialWrapperContext.BLOCK, Material.POTATOES, MaterialKey.from(142, 0))
        register(MaterialWrapperContext.BLOCK, Material.SKELETON_SKULL, MaterialKey.from(144, 0))
        register(MaterialWrapperContext.BLOCK, Material.WITHER_SKELETON_SKULL, MaterialKey.from(144, 1))
        register(MaterialWrapperContext.BLOCK, Material.ZOMBIE_HEAD, MaterialKey.from(144, 2))
        register(MaterialWrapperContext.BLOCK, Material.PLAYER_HEAD, MaterialKey.from(144, 3))
        register(MaterialWrapperContext.BLOCK, Material.CREEPER_HEAD, MaterialKey.from(144, 4))
        register(MaterialWrapperContext.BLOCK, Material.DOUBLE_RED_SANDSTONE_SLAB, MaterialKey.from(181, 0))
        register(MaterialWrapperContext.BLOCK, Material.SMOOTH_DOUBLE_RED_SANDSTONE_SLAB, MaterialKey.from(181, 8))
        register(MaterialWrapperContext.BLOCK, Material.SPRUCE_DOOR, MaterialKey.from(193, 0))
        register(MaterialWrapperContext.BLOCK, Material.BIRCH_DOOR, MaterialKey.from(194, 0))
        register(MaterialWrapperContext.BLOCK, Material.JUNGLE_DOOR, MaterialKey.from(195, 0))
        register(MaterialWrapperContext.BLOCK, Material.ACACIA_DOOR, MaterialKey.from(196, 0))
        register(MaterialWrapperContext.BLOCK, Material.DARK_OAK_DOOR, MaterialKey.from(197, 0))
    }

}